---
title: "Chapter 2-1 Practice"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(wooldridge)
ceosal1 <- wooldridge::ceosal1
salary.lm1 <- lm(salary ~ roe, data = ceosal1)
salary.lm2 <- lm(salary ~ 0 + roe, data = ceosal1)
salary.lm3 <- lm(salary ~ 1, data = ceosal1)
gradethis_setup()
tutorial_options(exercise.timelimit = 60)
knitr::opts_chunk$set(echo = FALSE)
```

## CEO Salaries and Return on Equity

Regress CEO salary on: 
1. ROE (with a constant - name this $salary.lm1$); 
2. ROE (without a constant - $salary.lm2$); 
3. Only a constant($salary.lm3$). Plot all three regression lines with a scatterplot of salary on ROE. 

```{r lmPractice, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r lmPractice-solution-1}
salary.lm1 <- lm(salary ~ roe, data = ceosal1)
salary.lm2 <- lm(salary ~ 0 + roe, data = ceosal1)
salary.lm3 <- lm(salary ~ 1, data = ceosal1)
```

```{r lmPractice-solution-2}
salary.lm1 <- lm(salary ~ roe, data = ceosal1)
salary.lm2 <- lm(salary ~ roe - 1, data = ceosal1)
salary.lm3 <- lm(salary ~ 1, data = ceosal1)
```

```{r lmPractice-check}
grade_code()
```

## Plotting the Regression Line

Plot the data for the previous exercise along with all three of the estimated regression lines. 

```{r plotPractice, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r plotPractice-solution}
plot(ceosal1$roe, ceosal1$salary, xlab = "Return on Equity", ylab = "Salary")
abline(salary.lm1)
abline(salary.lm2)
abline(salary.lm3)
```

```{r plotPractice-check}
grade_code()
```

