---
title: "Appendix B-1 Practice"
author: "Jim Bang"
output: pdf_document
classoption: landscape
description: "This tutorial practices probability and probability distributions."
---

```{r setup, include=FALSE}
```

## Appendix B, #5

Prior to jury selection for O.J Simpson's murder trial in 1995, a poll found that about 20% of the adult population believed Simpson was innocent (after much of the physical evidence in the case had been revealed to the public). Assume that the 12 jurors were selected randomly and independently from the population (although this turned out not to be true). 

1. Calculate the probability that the jury had at least one member who believed in Simpson's innocence prior to jury selection. 
2. Calculate the probability that the jury had at least two members who believed in Simpson's innocence.

## Exercise

Let X denote the prison sentence, in years (up to a hypothetical three-year maximum sentence), for people convicted of auto theft in a particular state in the United States. Suppose that the pdf of X is given by: 
$$ f(x) = (1/9)x^2, \text{ } 0 < x < 3 $$
Find the expected value and standard deviation of the prison sentence. 

