---
title: "Chapter 1-1 Practice"
author: "Jim Bang"
output: pdf_document
classoption: landscape
---

```{r setup, include=FALSE}

```

## Exercise

Here's a simple exercise with an empty code chunk provided for entering the answer.

Write the R code required to perform the following operations:

- $21 + 21$
- $5(4-1)^2-3$
- $\sqrt{1764}$

### Using Objects

R is an object-oriented language. The "assignment" operator, "<-" (keyboard shortcut: "Alt" + "-") computes the operation to the right and gives it name in your *environment* (see top-right pane in RStudio). Name the calculations from the previous exercise as indicated below.

- $21 + 21$: answer
- $5(4-1)^2-3$: life
- $\sqrt{1764}$: universe
- $ln(e^{42})$: everything

Display the objects in your environment using the `ls()` function. 

Note that in some cases you can use the "equal to" operator, "=", but only if the thing you're operating and the name of the object you're assigning are unambiguous. The direction of the "<-" operator points *from* the operation you mean for R to calculate and *to* the name you want to give to it. In fact, you may reverse the direction to assign from left to right, as in `21 + 21 -> answer`. 

### Defining and Evaluating Functions

If you can define an object you can write (and evaluate) your own function! A function can be a simple mathematical function, or it can be a long script that outputs several different values. Define the function, `quadratic`, as a function of *variable* `x` and *parameters* `a`, `b`, and `c` as 
$$f(x) = ax^2 + bx + c.$$ 
Then, evaluate $f(x) = 8x^2 - 6x - 12$ at $x = 3$

For the purposes of getting computational solutions, there is not really a difference between a parameter and a variable. Economically, we consider parameters (a, b, c, and d) to be *exogenous* - determined by nature (like preference parameters) or markets (like prices or income) - whereas we consider variables (x) to be *endogenous* - chosen by households (like quantities consumed) or firms (like amounts of a resource hired). 

## Vectors, Matrices, and Data Frames

### Vectors

Do the following: 

- Create the vector $a = \begin{pmatrix} 1 \\ 2 \\ 3 \\ 4 \\ 5 \\ 6 \end{pmatrix}$;
- Assign the value $a + 1$ to the object b;
- Assign the value $a + b$ to the object c;
- Assign the value $b + c$ to the object d;
- Calculate $\sqrt{d}$;

### Matrices

Do the following: 

- Create a matrix, A that splits the values of a across two columns;
- Create a matrix, B that duplicates the columns of A twice. 
- Extract the third column of B as a matrix named "b."

### Data Frames

1. *Load* "BeerData.RData" from "https://github.com/bangecon/metricsToTheFace/tree/master/inst/tutorials/Chapter01-1-Practice/BeerData.RData" into your workspace. 
2. *Read* "BeerData.csv" from "https://github.com/bangecon/metricsToTheFace/tree/master/inst/tutorials/Chapter01-1-Practice/BeerData.csv" as an object named "BeerDataCSV".

### Examining a Dataset
 
Display the first *five* rows of the mtcars dataset. Then, View the complete data frame in a new window.
