---
title: "Chapter 2"
subtitle: "The Simple Regression Model: Interpretation"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
author: 
  name: "Created by [Jim Bang](http://www.github.com/bangecon)"
  email: BangJamesT@sau.edu
  affiliation: "[St. Ambrose University](http://www.sau.edu)"
date: "`r format(Sys.Date(), '%d %b %Y')`"
always_allow_html: yes
editor_options: 
  markdown: 
    wrap: 72
description: "This tutorial practices interpretation of the linear coefficients and the properties of the OLS estimator."
---

<style type="text/css">
h1{font-size: 24pt}
h2{font-size: 20pt}
h3{font-size: 18pt}
h4,h5,h6{font-size: 16pt}
body{font-size: 16pt}
</style>

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(ggcheck)
gradethis::gradethis_setup()
tutorial_options(exercise.reveal_solution = FALSE)
knitr::opts_chunk$set(echo = FALSE)
```

## CEO Salaries and Sales

Use the `ceosal1` data to regress the *log* of CEO salaries on the *log* of sales. Name the results `ceosal.lm`

Summarize the results.

```{r lmPractice, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r lmPractice-solution}
ceosal1 <- wooldridge::ceosal1
ceosal.lm <- lm(log(salary) ~ log(sales), data = ceosal1)
summary(ceosal.lm)
```

```{r lmPractice-check}
grade_this({
  if (identical(.solution$call, .result$call)) 
    {
    pass(random_praise())
  }
  fail(random_encouragement())
})
```

Plot the data with the regression line. Number your figure and give it a title and descriptive axis labels using `labs()`. 

```{r lmPlot, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r lmPlot-setup}
ceosal1 <- wooldridge::ceosal1
ceosal.lm <- lm(log(salary) ~ log(sales), data = ceosal1)
```

```{r lmPlot-solution}
library(ggplot2)
ggplot(ceosal1, aes(log(sales), log(salary))) + 
  geom_point() + 
  geom_smooth(method = 'lm') + 
  labs(title = "Figure 1", subtitle = "CEO Salary versus Sales", 
       x = "ln(Sales)", y = "ln(Salary)") 
```

```{r lmPlot-check}
grade_this({
  if (uses_geoms(.result, c("smooth", "point"), exact = FALSE) &  
      uses_mappings(.result, aes(x = log(sales), y = log(salary))) & 
      uses_labels(.result, "title") & 
      uses_labels(.result, "x") & 
      uses_labels(.result, "y")) {
    pass(random_praise())
  }
  fail(random_encouragement(), " Make sure to give your figure a title and label the axes.")
})
```
