---
title: "Chapter 2-2 Practice"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(ggplot2)
ceosal1 <- wooldridge::ceosal1
gradethis_setup()
tutorial_options(exercise.timelimit = 60)
knitr::opts_chunk$set(echo = FALSE)
```

## CEO Salaries and Sales

Use the `ceosal1` data to regress the *log* of CEO salaries on the *log* of sales. Name the results `ceosal.lm`

Summarize the results.

```{r lmPractice, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r lmPractice-solution}
ceosal.lm <- lm(log(salary) ~ log(sales), data = ceosal1)
summary(ceosal.lm)
```

```{r lmPractice-check}
grade_this({if (!inherits(.result, c("summary.lm"))) {
    fail("Your class of your answer should be a summary of an lm object.")}
  if (round(.result$coefficients[2],4) != 0.2567) { 
    fail("The coefficient on log(Sales) should be about 0.26.") }
  pass()
})
```

Plot the data with the regression line. 

```{r lmPlot, exercise=TRUE, exercise.reveal_solution = FALSE}

```

```{r lmPlot-solution}
ggplot(ceosal1) + 
  geom_point(aes(log(sales), log(salary))) + 
  geom_smooth(aes(log(sales), log(salary)), formula = y ~ x, method = 'lm', se = FALSE) + 
  xlab("ln(Sales)") + ylab("ln(Salary") 
```

```{r lmPlot-check}
grade_this({if (!inherits(.result, c("gg", "ggplot"))) {
    fail("Your class of your answer should be c('gg', 'ggplot').")}
  if (length(.result) != 9) { 
    fail("You should use 'proto' plot functions to add layers to the same plot" ) }
  pass()
})
```
